### ISSUE TITLE
Add NPM package name for each component to doc pages

### ISSUE THREAD

**Issue by TiE23** [Bedrock-Layouts/Bedrock#1012]
**Is your feature request related to a problem? Please describe.**
Minutes ago I found myself having to guess the name of a package. It went something like this:
> "Oh, I think the inline cluster will work better for me than just inline here..."
> `yarn add @bedrock-layout/inlineCluster`
> _Bzzt!_
> "Nope. Why did I write camelCase anyway?"
> `yarn add @bedrock-layout/inlinecluster`
> _Bzzt!_
> "Oh, wait... is it 'inline cluster' or 'cluster inline'?"
> `yarn add @bedrock-layout/clusterinline`
> _Bzzt!_
> "I give up. Let me look at the docs."
> [Doesn't find any mention of the actual package name...]
> "Wow. Okay... Guess I gotta go to GitHub."
> [Navigates to GitHub, clicks on the packages directory...]
> `yarn add @bedrock-layout/inline-cluster`
> _Success!_
> "I should say something about this..."

**Describe the solution you'd like**
Either plainly list the package's name at the top of the [doc page](https://bedrock-layout.dev/?path=/docs/components-inlinecluster--api) for each component or be extra fancy and add a copy-to-clipboard button for it. Maybe even add an `npm install` and/or `yarn add` prefix.

**Comment by Jarvis1010** [comment]
Amazingly this used to be there, and somewhere along the line, it got lost.  The humor is this issue was perfect!

**Comment by Jarvis1010** [comment]
Thank you for the help
