### ISSUE TITLE
[use-forwarded-ref] Maximum update depth exceeded error on React Native

### ISSUE THREAD

**Issue by emehmet** [Bedrock-Layouts/Bedrock#1289]
When I use React native, I get Maximum update depth exceeded error. I guess it's related to the use-stateful-ref package.

React:17.0.1
React-native: 0.64.3
Expo : 44.0.6
windows 11
Android phone

**Comment by Jarvis1010** [comment]
It would probably be good to have the ref's statefulness be configurable

**Comment by emehmet** [comment]
yes,

`export const AssetMarkerRef = React.memo(
  React.forwardRef(({LAT, LON, ...props}: AssetMarkerProps, ref: React.Ref<MapMarkerRef | null>) => {

    const _map_ref = useForwardedRef(ref);
    React.useImperativeHandle(
      _map_ref,
      () => ({
        updateMarkerLocation: (curPos, zoom_percent) => {
            .....
        }
    })
    );
});
)`

like this

**Comment by Jarvis1010** [comment]
I am pushing up an update where you can opt-out of statefulness by passing in `{isStateful:false}` as a second parameter to `useForwardedRef`

**Comment by Jarvis1010** [comment]
This should be resolved with the latest addition
