### ISSUE TITLE
Install fails with React 18

### ISSUE THREAD

**Issue by markgreenwood** [Bedrock-Layouts/Bedrock#1321]
**Describe the bug**
`npm install @bedrock-layout/stack` fails when project uses React 18 with the following error:
```
npm ERR! Found: react@18.1.0
npm ERR! node_modules/react
npm ERR!   react@"^18.1.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.8 || ^17" from @bedrock-layout/stack@2.4.3
npm ERR! node_modules/@bedrock-layout/stack
npm ERR!   @bedrock-layout/stack@"*" from the root project
```
If I try installing with the `--legacy-peer-deps` option, my app fails to resolve dependencies in `@apollo/client` and/or `graphql-request`.

**To Reproduce**
1. Create a project with `npx create-react-app my-project --template typescript`.
2. Attempt to install `@bedrock-layout/stack` as stated in the description.
3. Should see the error message in the description.

**Expected behavior**
Should install.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.3.1

**Additional context**
Hey, @Jarvis1010. I realize React 18 is still hot off the press. Just wondering if there's any reason the peer dependencies can't be updated to include it yet.

**Comment by Jarvis1010** [comment]
You are right, I will try to do a review and confirm that there are not issues and get code pushed out within 24 hours

**Comment by huksley** [comment]
@Jarvis1010 Could you also update peerDependencies for @bedrock-layout/use-forwarded-ref?
It does not declare React 18
https://github.com/Bedrock-Layouts/Bedrock/blob/main/packages/use-forwarded-ref/package.json

Also
@bedrock-layout/use-stateful-ref
https://github.com/Bedrock-Layouts/Bedrock/blob/main/packages/use-stateful-ref/package.json
