### ISSUE TITLE
Docs loads blank

### ISSUE THREAD

**Issue by teachjenntech** [Bedrock-Layouts/Bedrock#1432]
**Describe the bug**
When going to https://www.bedrock-layout.dev/ the menu loads but the context of the selected option on the menu does not work.

**To Reproduce**

Go to https://www.bedrock-layout.dev/?path=/story/overview-bedrock-layout-primitives--page
CLick on any of the menu option
No error just blank

**Expected behavior**
That the instructions would load on the site and explain the overview 

**Screenshots**
![image](https://user-images.githubusercontent.com/108376073/186731372-885e24ab-ea5e-4281-94fb-2abd707d7906.png)
![image](https://user-images.githubusercontent.com/108376073/186731403-a6de017d-f4d5-48eb-9ae9-9f397321c771.png)
![IMG_97B06FA7D2A7-1](https://user-images.githubusercontent.com/108376073/186731808-88386e6f-df55-4945-abd1-2e32394153c9.jpeg)

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser Macbook: Safari

**Smartphone (please complete the following information):**
 - Device: iPhone 12 pro
 - Browser safari 

**Additional context**

**Comment by Jarvis1010** [comment]
This issue has been fixed.  The docs should be loading correctly now.
