### ISSUE TITLE
`<Box>` component referenced in documentation but not exported

### ISSUE THREAD

**Issue by DDunc** [Bedrock-Layouts/Bedrock#1443]
**Describe the bug**
The `<Box>` component not defined by Bedrock library but is referenced in documentation and layout examples. It appears to be the intention is for it to be a primitive rather than just a div.

**To Reproduce**
1. Go to [layout examples](https://www.bedrock-layout.dev/?path=/docs/examples-web-dev--holy-grail-layout).
4. See that  the `<Box as="main"` is undefined and not exported.

**Expected behavior**
The documentation should include Bedrock elements which are exported or HTML elements. 

Love this library! I just found the missing component to be a hinderance for it to just work out of the box. Might also be a good idea to just include the import statements in a comment rather than describing them in prose above.

**Comment by Jarvis1010** [comment]
My apologies for the confusion.  Box in the docs is not actually one of the layout components.  It was intended to just represent any element or component that you may wish to place in there.  I do see how it can be confusing though.  I will look at replacing them with just raw elements, to make it less confusing.
