### ISSUE TITLE
AppBoundary `overflow: hidden`?

### ISSUE THREAD

**Issue by martindines** [Bedrock-Layouts/Bedrock#1874]
Hi @Jarvis1010 ,

Apologies, this isn't a bug report. I'm wondering why AppBoundary [sets the overflow property to `hidden`](https://github.com/Bedrock-Layouts/Bedrock/blob/main/packages/appboundary/src/index.tsx#L31)? This disables scrolling when page height exceeds the viewport height. Would it be better to remove this property and rely on the default browser behaviour here (auto)?

Thanks for Bedrock, it's very handy!

Martin

**Comment by Jarvis1010** [comment]
Sorry my notifications were off and I didn't see this right away.  Yes that makes sense, if you would like to do a PR I would be happy to review it.

**Comment by Jarvis1010** [comment]
Just to update.  Had a lot of issues come up I will work on this this week.
