### ISSUE TITLE
BedRock-Layout Doc broken

### ISSUE THREAD

**Issue by mstalenhoef** [Bedrock-Layouts/Bedrock#2002]
All pages except 'Contributing' are broken.

![image](https://github.com/Bedrock-Layouts/Bedrock/assets/19531042/4212f858-15ce-49f5-aec7-f851766159de)

**Comment by Jarvis1010** [comment]
There is a yarn lock issue in the dependabot updates.  Pushing up a fix now. Will confirm when it is working

**Comment by Jarvis1010** [comment]
https://www.bedrock-layout.dev/

Is now working correctly.  Thank you for your contributions.

**Comment by mstalenhoef** [comment]
Thank you for your rapid reaction. I'm looking forward to learning this framework.

**Comment by Jarvis1010** [comment]
Feel free to message or open issues if there is anything incorrect or confusing Justin Travis Waith-MairEl ago. 12, 2023, a la(s) 12:28 p.m., Martijn Stalenhoef ***@***.***> escribió:﻿
Thank you for your rapid reaction. I'm looking forward to learning this framework.
