### ISSUE TITLE
Documentation syntax is wrong

### ISSUE THREAD

**Issue by gorkamolero** [Bedrock-Layouts/Bedrock#318]
**Describe the bug**
The documentation syntax anywhere for React.forwardRef syntax is wrong.

**To Reproduce**
1. Go to https://bedrock-layout.dev/src-components-use-container-query

**Expected behavior**
There should be a parenthesis outside the function:
```
React.forwardRef((props, ref) => (
  <button ref={ref} className="FancyButton">
    {props.children}
  </button>
));
```
Example: https://reactjs.org/docs/forwarding-refs.html

**Comment by Jarvis1010** [comment]
This is fixed and I will push it up soon. Thanks for the help
