### ISSUE TITLE
Question about FlexBox

### ISSUE THREAD

**Issue by httpete** [Bedrock-Layouts/Bedrock#336]
Hi,

I am really impressed by what you are doing here. I am trying to find out how to transpose css notions to your layout notions.
I am laying out a really typical Alert, https://chakra-ui.com/docs/feedback/alert like this. 

Traditionally I'd think FlexBox. But what layout notion does that map to? Columns? I like insulating my consumers from any notion of Flex.

**Comment by Jarvis1010** [comment]
This looks like a `Split` with it's `fraction` prop set to `auto-start`.  Along with that I looks like you have a PadBox outer wrapper

**Comment by httpete** [comment]
Thank you @Jarvis1010 I will fiddle around. That was the first question my team had - how do we figure out which one to use? 
In my mind I always separated page layout sorts of things from internal component layout concerns, but with your rich system based on that well thought through project, maybe this is the holy grail.

**Comment by Jarvis1010** [comment]
My apologies, I didn't see the "x" on the far right.  

Here is how I would do that:

[https://stackblitz.com/edit/react-ts-axuadj?file=Alert.tsx](https://stackblitz.com/edit/react-ts-axuadj?file=Alert.tsx)

Basically we are nesting a `Split` in a `Split` (inception, I know) both with `auto-start` as the the `fraction` prop.  Then I use an `InlineCluster` component around the `x` withe `justify="end"` prop to move it to the right

I do have one question, Given that a `Split` component is designed to put two things next to each other, what would you expect the behavior to be if you put in 3 things.  Currently, it wraps, but should it keep adding elements indefinitely on the same line? I see the justification to do both, so I was wondering what your thoughts were on that

**Comment by httpete** [comment]
Thank you - 
https://stackblitz.com/edit/react-ts-kqhk2c?file=Alert.tsx
This isn't the desired result. In flexbox you'd have three columns, the first and last being set to a hard coded width, so the middle just grows to the entire space in between.

**Comment by Jarvis1010** [comment]
You are using the wrong prop name.  it should be `fraction` singular and not `fractions` plural

**Comment by httpete** [comment]
Boom works! I wonder what your thoughts are on this approach vs FlexBox.

**Comment by Jarvis1010** [comment]
There are give and takes using both approaches. Using bedrock you have reusable parts but you might need a more parts to make it work. Where using flex box means you may need fewer parts but they are very specific and less reusable(which isn't a bad thing.  Code reuse can be over rated)

**Comment by httpete** [comment]
> You are using the wrong prop name. it should be `fraction` singular and not `fractions` plural

It would be nice if there were descriptions for what terms like "auto-start" mean in the doc.

**Comment by Jarvis1010** [comment]
I do acknowledge that the docs could be much improved and really is something I want to look at going forward.  Thank you for your help and feedback

**Comment by httpete** [comment]
@Jarvis1010 the doc is actually wrong :

https://bedrock-layout.dev/src-components-split

it has "fractions" plural in the properties table below.

**Comment by Jarvis1010** [comment]
That's so awesome!  I am so happy this was useful and thanks again for pointing out the error. It should be fixed now
