### ISSUE TITLE
gutter="none" does 32px on Inline

### ISSUE THREAD

**Issue by httpete** [Bedrock-Layouts/Bedrock#370]
https://bedrock-layout.dev/src-components-inline

Not seeing none come through at all.

**Comment by httpete** [comment]
I found that I was doing this in my themeprovider theme, and the 0 int was killing it.

  spacing: {
    none: 0,
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '40px',
  },

**Comment by Jarvis1010** [comment]
Interesting.  I am pretty sure I know what us causing it.

**Comment by httpete** [comment]
Also doc update: Many places like this: https://bedrock-layout.dev/src-components-inline need the xxs for gutter.

**Comment by Jarvis1010** [comment]
this is fixed in the latest updates

**Comment by Jarvis1010** [comment]
Closing as this should be fixed
