### ISSUE TITLE
TypeScript and ThemeProvider support for props

### ISSUE THREAD

**Issue by httpete** [Bedrock-Layouts/Bedrock#405]
When using a component it's good to ensure that no one can provide a value that the component can't accept. My VsCode autosuggested:
`
 <PadBox padding="xlXXl" />`

And typescript doesn't yell.  How can we make Bedrock typesafe?

**Comment by Jarvis1010** [comment]
This is a valid option now

**Comment by httpete** [comment]
@Jarvis1010 sorry - not sure what you mean - this ability is there now, or this is a good idea? I am not seeing it in VsCode.

**Comment by Jarvis1010** [comment]
Sorry I responded on my phone during a meeting I was in.  That is a valid spacing type now: [https://bedrock-layout.dev/src-components-spacing-constants](https://bedrock-layout.dev/src-components-spacing-constants)

**Comment by httpete** [comment]
But the autocompletion (doing ctrl+space) in vscode should suggest them based on the provided spacing constants in the styled-components ThemeProvider.

**Comment by httpete** [comment]
xlXXl is coming from: 
https://github.com/Bedrock-Layouts/Bedrock/blob/922d8708104061e261d53ace8ddf3a05f9c1cb78/packages/spacing-constants/src/index.tsx
and isn't one of the valid options for PadBox.

I guess you could first make sure that each component returns the types for each prop, that happen to match to the themeProvider keys... But better would be to get the typing from styled-components (Which is possible) 
https://styled-components.com/docs/advanced#via-withtheme-higherorder-component

But maybe option 1 is fine and proper.

**Comment by Jarvis1010** [comment]
@httpete attached is my basic idea of how to solve this.  Basically, accept the theme provider spacing types, but fall back to the default spacing types:

https://codesandbox.io/s/nice-microservice-3nthf?file=/src/App.tsx

To facilitate this, we would move to have a `0px` spacing fallback if none/incorrect values for gutters are provided and make the gutters be explicitly defined. This would be a breaking change, which I am ok with since I would prefer to move the modules to named exports instead of default exports anyway.

Let me know what you think.

**Comment by httpete** [comment]
@Jarvis1010 I think this is spot on.

**Comment by Jarvis1010** [comment]
Ok I will start working on this, I will be pushing an update that will let me update components one at a time.  I know PadBox and Inline are on your radar.  Anything else?

**Comment by httpete** [comment]
After my eval we need: Inline, PadBox, Stack, Center and Split. Thank you

**Comment by Jarvis1010** [comment]
Stack and Split have been updated to a 2.0.0 release if you want to start incorporating it. I will work on the other two as soon as I am able. The Center doesn't use spacing, but I will be updating that to a named export at the very least

**Comment by Jarvis1010** [comment]
Inline and PadBox are also updated

**Comment by Jarvis1010** [comment]
All the spacing components are updated to use the theme types
