### ISSUE TITLE
One Resize observer to rule em all

### ISSUE THREAD

**Issue by gorkamolero** [Bedrock-Layouts/Bedrock#511]
**Is your feature request related to a problem? Please describe.**
The library can perform badly if you have it all over the place (many resize observers -> https://github.com/WICG/resize-observer/issues/59)

**Describe the solution you'd like**
Trying to use one Resize observer and subscribe any element to that. Kind of like this library promises but it just doesn't work -> https://github.com/envato/react-resize-observer-hook#readme

Awesome work! Your library is getting pretty great

**Comment by Jarvis1010** [comment]
Thank you so much!  This is a great idea

**Comment by Jarvis1010** [comment]
This should be done now.  As of right now, it The most that should exist is two Resize observers, one for MasonryGrid and one for anything using the useContainer hook, including the switchers.

Thanks again

**Comment by gorkamolero** [comment]
Nice!
