### ISSUE TITLE
AppBoundary has untyped Props / Breakpoint doc

### ISSUE THREAD

**Issue by httpete** [Bedrock-Layouts/Bedrock#560]
https://github.com/Bedrock-Layouts/Bedrock/blob/master/packages/appboundary/src/index.tsx

It should be overridable via the theme as well no? Luckily 1920 is exactly what we want, but shouldn't this come from the spacing-constants and be overridable like spacing?

**Comment by Jarvis1010** [comment]
This is currently hardcoded, but I want to make it work with [System UI Theme specification](https://system-ui.com/theme)

**Comment by Jarvis1010** [comment]
Specifically it should be under the sizes key

**Comment by httpete** [comment]
I'd like to be able to specify it globally - we are going to use it as a clamp WITHIN the app body - not around the entire outer navigation. We have a leftnav that also needs to be considered. Bottom line is I want the AppBoundary to respect the max-inline-size that we set, just as if <Center maxWidth={XXX}>. Doable?

**Comment by Jarvis1010** [comment]
There is a Center component that allows you to set the `max-inline-size` via props.  The bigger question for me is, wouldn't exposing the max-width via props be an easier and more intuitive API than through the theme.  And if that's the case, what value is AppBoundary giving that the Center Component isn't giving.

**Comment by Jarvis1010** [comment]
I'm still thinking on this. We could have sizes but the sizes keys wouldn't be able to be changed

**Comment by Jarvis1010** [comment]
@httpete Here are my thoughts and you let me know what you think as far as it's usefulness.  We have some `size` values that can be overridden via the Theme provider.  It should follow the same types as the `space` values, e.g.

```javascript
{
   size: {
      "xx-large": 1920,
      "large": "40rem",
     /* etc */
   }
}
```

Then for the AppBoundary we expose an optional `maxWidth` prop that either takes a `SizeOption` type or string.  If no value is provided it will fall back to the `1920px`

This is the rough draft of the idea so feedback would be most welcome.  Thoughts?

**Comment by httpete** [comment]
It's a good idea - and it's important to stress that you should EXPORT the options so that it can be used in Storybook / controls. I had to duplicate them for now.
