### ISSUE TITLE
Pad Box custom spacing

### ISSUE THREAD

**Issue by fpw23** [Bedrock-Layouts/Bedrock#890]
**Is your feature request related to a problem? Please describe.**
I am trying to use the padbox component to pixel match a design and it is impossible because I can not override the Top/Left/Bottom/Right with specific values.  I can only use the named preset values 

**Describe the solution you'd like**
I want to be able to pass in named and specific values for the padbox padding property for Top/Left/Bottom/Right.  As a developer I can't enforce the preset padding requirements on designers but I still have to match their designs.

**Describe alternatives you've considered**
I am able to achieve my desired outcome by using the attr method of styled components and using the padbox as a base but it is a lot of extra coding.  It would be much cleaner if I could just manually set values instead of using preset constraints.

**Additional context**
![image](https://user-images.githubusercontent.com/6162217/138869416-9c412871-fbc5-4967-8475-a765395c4524.png)

having the option to pass 10rem or a constant like 'lg'/'sm' would give me more flexibility.

**Comment by Jarvis1010** [comment]
This is being addressed in #1162 and will be closed in the next release
