### ISSUE TITLE
Grammar, spelling, and editing of Components Docs

### ISSUE THREAD

**Issue by Jarvis1010** [Bedrock-Layouts/Bedrock#943]
The following components need to be reviewed for Grammar, spelling, and just overall clarity.  I would love help on any or all of these:

- [ ] AppBoundary
- [ ] Center
- [ ] Columns
- [ ] Cover
- [ ] Frame
- [ ] Grid
- [ ] InlineCluster
- [ ] Inline
- [ ] MasonryGrid
- [ ] PadBox
- [ ] Reel
- [ ] Split
- [ ] Stack

Feel free to reference this issue in any PRs you submit.

**Comment by rajatk16** [comment]
@Jarvis1010 Got a doubt about InlineCluster. 

InclineCluster's docs mention a switchAt prop, but looking at its code I can't see it.

**Comment by Jarvis1010** [comment]
You're correct it doesn't have a switchAt prop.  I must have copy and pasted that from the Inline page
